image: registry.gitlab.com/ks-sakhautdinova/datavault_project/dbt-sqlserver:1.1

stages:
  - test
  - deploy

variables:
  WORK_DIR: "$CI_PROJECT_DIR/demo_dv_dbt"
  DBT_PROFILES_DIR: "$WORK_DIR"

default:
  before_script:
    - cd "$WORK_DIR"
    - pwd

test_connection:
  tags: [linux, dbt, sqlserver]
  stage: test
  only:
    - dev
    - main
  variables:
    DBT_TARGET: "dev"
  script:
    - echo "Testing connection..."
    - dbt deps
    - dbt debug --profiles-dir "$DBT_PROFILES_DIR" --target dev
  allow_failure: true

deploy_dev:
  tags: [linux, dbt, sqlserver]
  stage: deploy
  only:
    - dev
  variables:
    DBT_TARGET: "dev"
  script:
    - echo "=== Deploy dbt DEV ==="
    - dbt deps
    - dbt run --target dev --profiles-dir "$DBT_PROFILES_DIR"
    - dbt test --target dev --profiles-dir "$DBT_PROFILES_DIR"
  artifacts:
    when: always
    paths:
      - demo_dv_dbt/target/

deploy_prod:
  tags: [linux, dbt, sqlserver]
  stage: deploy
  only:
    - main
  variables:
    DBT_TARGET: "prod"
  script:
    - echo "=== Deploy dbt PROD ==="
    - dbt deps
    - dbt run --target prod --profiles-dir "$DBT_PROFILES_DIR"
    - dbt test --target prod --profiles-dir "$DBT_PROFILES_DIR"
  when: manual
  artifacts:
    when: always
    paths:
      - demo_dv_dbt/target/